# Surface Normal Model Utility functions

In [2]:
import sys
sys.path.append('./models/')
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time
import os

## Test of Loss function for surface normal vectors

In [9]:
# x = torch.autograd.Variable(torch.randn(3, 5) )
# y = torch.autograd.Variable(torch.randn(3, 5) )
x = torch.autograd.Variable(torch.randn(2, 3, 5, 5) )
y = torch.autograd.Variable(torch.randn(2, 3, 5, 5) )
print('Orig vector (only first one printed):')
print(x)
target2 = torch.autograd.Variable(torch.tensor([1], dtype=torch.float))

#CosineEmbeddingLoss
loss_fn = torch.nn.CosineEmbeddingLoss(reduction='none') #NOTE: elementwise_mean apparently doesn't work
z0 = loss_fn(x, y, target2)
print('\nCosineEmbeddingLoss')
print(z0)

#CosineSimilarity
cos = nn.CosineSimilarity(dim=1, eps=1e-6)
loss_fn = 1 - cos(x,y)
print('\nCosine Similarity Matrix')
print(loss_fn)
loss_fn = torch.mean( loss_fn )
print('Cosine Similarity mean loss')
print(loss_fn)
        

#Custom Code
a = (x.norm(p=2,dim=0)*y.norm(p=2,dim=0))
b = torch.sum(x*y,1)
a[a==0] = 1
b[a==0] = 1
distance = 1 - ( b / a)
totloss = torch.mean(distance)
print('\nShuran\'s Loss func')
print(totloss)

Orig vector (only first one printed):
tensor([[[[-0.2534, -0.5149,  1.6493,  0.7740, -2.1743],
          [ 0.9406, -0.7726, -0.5870, -3.0862, -0.2586],
          [-0.2336,  0.1946, -0.5431,  0.2082, -0.4474],
          [ 2.0481, -0.2056,  0.4359, -0.7448, -0.3045],
          [-0.2991, -0.0076,  0.0273,  1.1128, -0.5613]],

         [[-0.4597,  0.0863, -0.9023,  0.0209,  0.8687],
          [-0.8005,  0.1080,  0.8968,  0.2016, -1.4164],
          [ 1.4485,  1.5667, -0.5037, -0.4473, -0.8389],
          [-0.6640,  0.8778,  0.2664,  1.0980,  0.9897],
          [-2.4417,  0.1973, -0.3053,  0.1241, -1.6185]],

         [[ 1.2266, -0.0581, -1.4383, -0.8589,  0.7094],
          [-0.0147,  1.3564,  0.9895,  0.9950,  0.8161],
          [ 0.2097, -0.2638,  2.4874,  2.1679, -0.7313],
          [ 2.0223, -0.7119, -0.7906,  1.4216, -0.1946],
          [ 1.0260, -0.7382,  0.6290,  0.7016,  0.9752]]],


        [[[ 0.0475,  0.4140,  0.3558,  0.9755,  0.2723],
          [-1.8639,  0.9670, -0.3631, -0.1

RuntimeError: The shape of the mask [3, 5, 5] at index 0 does not match the shape of the indexed tensor [2, 5, 5] at index 0

## Test of Normalization Function for surface normal vectors

In [9]:
k = torch.tensor([[0.5, 0.1],[0.2,0.5]], dtype=torch.float)
print('Tensor k:')
print(k)
print('\nNormalized Tensor, along dim 1 (column):')
print(nn.functional.normalize(k, p=2, dim=1))

Tensor k:
tensor([[0.5000, 0.1000],
        [0.2000, 0.5000]])

Normalized Tensor, along dim 1 (column):
tensor([[0.9806, 0.1961],
        [0.3714, 0.9285]])
